version: '3.8'

services:
  # PHP-FPM Container
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network

  # Nginx Container
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Zugriff über http://localhost:8080
    volumes:
      - ./web:/var/www/html
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge