version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "801:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
