version: '3.8'

services:
  # NGINX Service
  nginx:
    image: nginx:stable-alpine
    container_name: my_nginx_server
    ports:
      - "801:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  # PHP Service
  php-fpm:
    image: php:8.2-fpm-alpine
    container_name: my_php_fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
